WebPage:
  BaseUrl: "https://www.sodimac.com.uy/sodimac-uy/category/cat20864/herramientas-manuales/"
  ValidationUrl: "https://www.sodimac.com.uy/sodimac-uy/product/"
  MaxProducts: 60
  Headless: true
  PaginationParam: "currentpage"
  StartPage: 1
  MaxPages: 10
  WaitForSelector: ".product-listing-selector"  # o tu selector correcto